# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - meeting-app-be

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DATABASE_URL: mongodb+srv://Khanh:Khanh20521455@app-meeting.jw6rqeq.mongodb.net/app-meeting?retryWrites=true&w=majority
  JWT_SECRET: qF=Czau.u%M(ZcdrLFGbVCJN}VH+u_}mHhTijuPNjg2V;c}N}F:Q{zY:Km$g/DBhp#_%meowmeow$tB=Fzv{ATYih2rB}A?:3eGB

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: yarn install, build
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn upgrade
          npx prisma generate
          npx prisma db push
          yarn build
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'meeting-app-be'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BFDBD2585DD14EEC977853BEB6FF3D0D }}
          package: .
